name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install development dependencies
        run: pip install flake8 mypy black semgrep safety reviewdog

      - name: Lint code with flake8
        id: flake8
        run: flake8 . > flake8_report.txt || true

      - name: Reviewdog - Flake8
        uses: reviewdog/action-flake8@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: error

      - name: Type check with mypy
        id: mypy
        run: mypy . > mypy_report.txt || true

      - name: Reviewdog - Mypy
        uses: reviewdog/action-mypy@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: error

      - name: Format code with black
        id: black
        run: black --check . > black_report.txt || true

      - name: Reviewdog - Black
        uses: reviewdog/action-black@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: error

      - name: Security scan with semgrep
        id: semgrep
        run: semgrep --config p/ci > semgrep_report.txt || true

      - name: Reviewdog - Semgrep
        uses: reviewdog/action-semgrep@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: error

      - name: Security scan with safety
        id: safety
        run: safety check > safety_report.txt || true

      - name: Reviewdog - Safety
        uses: reviewdog/action-safety@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: error
