name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install development dependencies
        run: pip install flake8 mypy black semgrep safety reviewdog

      - name: Lint code with flake8
        run: flake8 .
        continue-on-error: true

      - name: Reviewdog - Flake8
        uses: reviewdog/action-runner@v1
        with:
          name: flake8
          token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: flake8
          reporter: github-pr-check
          level: error
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Type check with mypy
        run: mypy .
        continue-on-error: true

      - name: Reviewdog - Mypy
        uses: reviewdog/action-runner@v1
        with:
          name: mypy
          token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: mypy
          reporter: github-pr-check
          level: error
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Format code with black
        run: black --check .
        continue-on-error: true

      - name: Reviewdog - Black
        uses: reviewdog/action-runner@v1
        with:
          name: black
          token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: black
          reporter: github-pr-check
          level: error
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Security scan with semgrep
        run: semgrep --config p/ci
        continue-on-error: true

      - name: Reviewdog - Semgrep
        uses: reviewdog/action-runner@v1
        with:
          name: semgrep
          token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: semgrep
          reporter: github-pr-check
          level: error
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Security scan with safety
        run: safety check
        continue-on-error: true

      - name: Reviewdog - Safety
        uses: reviewdog/action-runner@v1
        with:
          name: safety
          token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: safety
          reporter: github-pr-check
          level: error
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
