name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install development dependencies
        run: pip install flake8 mypy black semgrep safety

      - name: Lint code with flake8
        id: flake8
        run: flake8 . | tee flake8_report.txt
        continue-on-error: true

      - name: Reviewdog - Flake8
        uses: reviewdog/action-flake8@v3
        with:
          reporter: github-pr-check
          filter_mode: file
          fail_on_error: false
          level: warning
        env:
          REVIEWDOG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Type check with mypy
        id: mypy
        run: mypy . | tee mypy_report.txt
        continue-on-error: true

      - name: Reviewdog - Mypy
        uses: tsuyoshicho/action-mypy@v4
        with:
          reporter: github-pr-check
          filter_mode: file
          fail_on_error: false
          level: warning
        env:
          REVIEWDOG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Format code with black
        id: black
        run: black --check . | tee black_report.txt
        continue-on-error: true

      - name: Reviewdog - Black
        uses: reviewdog/action-black@v3
        with:
          reporter: github-pr-check
          filter_mode: file
          fail_on_error: false
          level: warning
        env:
          REVIEWDOG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Security scan with semgrep
        id: semgrep
        run: semgrep --config p/ci | tee semgrep_report.txt
        continue-on-error: true

      - name: Reviewdog - Semgrep
        uses: g-wilson/action-semgrep@v1
        with:
          reporter: github-pr-check
          filter_mode: file
          fail_on_error: false
          level: warning
        env:
          REVIEWDOG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # << Temploraray removed Safety >>
      # -  name: Setup Reviewdog
      #    uses: reviewdog/action-setup@v1
      #    with:
      #      reviewdog_version: latest

      # - name: Security scan with safety
      #   id: safety
      #   run: safety check --json > safety_report.json
      #   continue-on-error: true

      # - name: Reviewdog - Safety
      #   run: reviewdog -f=sarif -name="safety" -reporter=github-pr-check -level=warning < safety_report.json
      #   env:
      #     REVIEWDOG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
